services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fhirdb
      POSTGRES_USER: fhiruser
      POSTGRES_PASSWORD: fhirpassword
    ports:
      - "5432:5432"
    volumes:
      - hl7_pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP protocol port (used by producer/consumer)
      - "15672:15672"  # management UI — visit http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  hl7_pg_data:
